# Generated by Django 4.2.29 on 2026-04-01 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Store Code')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Store Name')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('manager_name', models.CharField(blank=True, max_length=50, verbose_name='Manager Name')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'store',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('warning_threshold', models.IntegerField(default=10, verbose_name='Warning Threshold')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='medicine.medicine')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='inventory.store')),
            ],
            options={
                'db_table': 'inventory',
                'ordering': ['id'],
                'unique_together': {('store', 'medicine')},
            },
        ),
    ]
