# Generated by Django 4.2.29 on 2026-04-01 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Manufacturer Name')),
                ('contact_person', models.CharField(blank=True, max_length=50, verbose_name='Contact Person')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Contact Phone')),
            ],
            options={
                'db_table': 'manufacturer',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MedicineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Category Name')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
            ],
            options={
                'db_table': 'medicine_category',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Medicine Code')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Medicine Name')),
                ('specification', models.CharField(max_length=100, verbose_name='Specification')),
                ('unit', models.CharField(default='box', max_length=20, verbose_name='Unit')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Purchase Price')),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Retail Price')),
                ('approval_number', models.CharField(blank=True, max_length=60, verbose_name='Approval Number')),
                ('production_date', models.DateField(blank=True, null=True, verbose_name='Production Date')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicines', to='medicine.medicinecategory')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicines', to='medicine.manufacturer')),
            ],
            options={
                'db_table': 'medicine',
                'ordering': ['id'],
            },
        ),
    ]
