-- Compatibility note
-- The announcement table definition has been merged into schema.sql.
-- For a fresh deployment, execute schema.sql and then init_data.sql.
-- This file is intentionally kept as a no-op for backward compatibility.
