-- Compatibility note
-- The sales-related schema changes have been merged into schema.sql.
-- For a fresh deployment, execute schema.sql and then init_data.sql.
-- This file is intentionally kept as a no-op for backward compatibility.
